import { ArrowRight, Clock3, Mail, MapPin, Instagram, Linkedin } from "lucide-react";
import { Link } from "react-router-dom";
import { ConsultationForm, Eyebrow, PageIntro, PageShell, SOCIAL_LINKS } from "@/components/LuminorSite";

export default function Contact() {
  return <PageShell><main><PageIntro eyebrow="Let’s talk" title={<>Put a little more <span className="italic text-[#ffbf00]">light</span> into the room.</>} description="Tell us what you’re building, where you’re stuck, or what you’re curious about. We’ll bring the useful questions." />
    <section className="mx-auto grid max-w-[1320px] gap-10 px-5 pb-24 lg:grid-cols-[0.72fr_1.28fr] lg:px-8 lg:pb-32" data-testid="contact-form-section"><div className="rounded-3xl bg-[#1a1814] p-8 text-[#fffbf2] sm:p-10"><Eyebrow>Start here</Eyebrow><h2 className="mt-6 font-serif text-4xl leading-tight">Good conversations make better work.</h2><p className="mt-5 text-sm leading-7 text-[#b9b1a2]">Share a little context and we’ll come back with a thoughtful next step within one business day.</p><div className="mt-14 space-y-6 text-sm"><div className="flex gap-3"><Clock3 className="size-4 shrink-0 text-[#ffbf00]" /><span>Replies within 1 business day</span></div><div className="flex gap-3"><Mail className="size-4 shrink-0 text-[#ffbf00]" /><a href="mailto:hello@luminormedia.co" data-testid="contact-email-link">hello@luminormedia.co</a></div><div className="flex gap-3"><MapPin className="size-4 shrink-0 text-[#ffbf00]" /><span>Bengaluru · Chitradurga · Karnataka · India</span></div><div className="flex items-center gap-3 pt-3 border-t border-[#332f27]"><a href={SOCIAL_LINKS.instagram} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-xs text-[#b9b1a2] transition hover:text-[#ffbf00]" data-testid="contact-instagram-link"><Instagram className="size-4 text-[#ffbf00]" /> Instagram</a><span className="text-[#575247]">/</span><a href={SOCIAL_LINKS.linkedin} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-xs text-[#b9b1a2] transition hover:text-[#ffbf00]" data-testid="contact-linkedin-link"><Linkedin className="size-4 text-[#ffbf00]" /> LinkedIn</a></div></div></div><div className="rounded-3xl border border-[#e8e1ce] bg-white p-7 sm:p-10"><Eyebrow>Tell us more</Eyebrow><h2 className="mt-5 font-serif text-4xl tracking-tight">Let’s make your next move clearer.</h2><div className="mt-8"><ConsultationForm /></div></div></section>
    <section className="border-t border-[#e8e1ce] bg-[#f7f1e3]" data-testid="contact-reassurance-section"><div className="mx-auto flex max-w-[1320px] flex-col justify-between gap-6 px-5 py-16 sm:flex-row sm:items-center lg:px-8"><p className="max-w-xl font-serif text-3xl tracking-tight">Not ready for a full conversation yet?</p><Link to="/faq" className="inline-flex items-center text-sm font-semibold" data-testid="contact-faq-link">Start with the FAQs <ArrowRight className="ml-2 size-4" /></Link></div></section>
  </main></PageShell>;
}