import { ArrowRight, Clock3, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Eyebrow, PageIntro, PageShell } from "@/components/LuminorSite";

const articles = [
  ["Algorithm updates", "The quiet shift from reach to resonance", "4 min read", "Why the brands winning right now are optimizing for the second action, not the first impression.", "https://images.unsplash.com/photo-1572177147505-c44e97033921?auto=format&fit=crop&w=1100&q=85"],
  ["Viral content science", "A slower, smarter way to make a scroll stop", "6 min read", "A creative director’s field notes on building moments that earn attention without begging for it.", "https://images.unsplash.com/photo-1647427854253-b92bb40c9330?auto=format&fit=crop&w=1100&q=85"],
  ["Paid social strategy", "The creative performance loop", "5 min read", "What changes when your media team and your content team stop speaking in separate rooms.", "https://images.unsplash.com/photo-1612544409025-e1f6a56c1152?auto=format&fit=crop&w=1100&q=85"],
  ["Brand thinking", "Your brand is a feeling before it is a funnel", "7 min read", "A practical guide to building consistency that never feels like repetition.", "https://images.unsplash.com/photo-1586732711591-12c04655338f?auto=format&fit=crop&w=1100&q=85"],
];
const categories = ["All", "Algorithm updates", "Viral content science", "Paid social strategy", "Brand thinking"];

export default function Insights() {
  const [category, setCategory] = useState("All");
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => articles.filter(([group, title, , text]) => (category === "All" || group === category) && `${group} ${title} ${text}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <PageShell><main><PageIntro eyebrow="The Luminor letter" title={<>Ideas for a <span className="italic text-[#ffbf00]">brighter</span> feed.</>} description="Thoughts on creative strategy, social culture, and the small decisions that make a brand feel like it has a pulse." />
    <section className="mx-auto max-w-[1320px] px-5 pb-24 lg:px-8 lg:pb-32" data-testid="insights-section"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2" role="tablist" aria-label="Insight categories">{categories.map((item) => <button type="button" key={item} onClick={() => setCategory(item)} className={`rounded-full border px-4 py-2 text-xs font-semibold transition ${category === item ? "border-[#1a1814] bg-[#1a1814] text-[#fffbf2]" : "border-[#e8e1ce] hover:border-[#ffbf00]"}`} data-testid={`insights-filter-${item.toLowerCase().replaceAll(" ", "-")}-button`}>{item}</button>)}</div><div className="relative w-full sm:max-w-xs"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#8c8474]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search insights" aria-label="Search insights" className="h-10 w-full rounded-full border border-[#e8e1ce] bg-white pl-10 pr-4 text-sm outline-none focus:border-[#ffbf00]" data-testid="insights-search-input" /></div></div><div className="mt-12 grid gap-6 md:grid-cols-2">{filtered.map(([group, title, read, text, image], index) => <article key={title} className={`group overflow-hidden rounded-3xl border border-[#e8e1ce] bg-white ${index === 0 ? "md:col-span-2 md:grid md:grid-cols-[1fr_1fr]" : ""}`} data-testid={`insight-card-${index}`}><div className="min-h-64 overflow-hidden"><img src={image} alt={title} className="size-full min-h-64 object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /></div><div className="flex flex-col justify-between p-7 sm:p-9"><div><p className="eyebrow">{group}</p><h2 className="mt-5 font-serif text-3xl leading-tight tracking-tight sm:text-4xl">{title}</h2><p className="mt-4 text-sm leading-6 text-[#575247]">{text}</p></div><Link to="/contact" className="mt-8 inline-flex items-center text-sm font-semibold" data-testid={`insight-card-${index}-link`}>Read the thinking <ArrowRight className="ml-2 size-4 transition group-hover:translate-x-1" /></Link></div></article>)}</div></section>
    <section className="bg-[#1a1814] text-[#fffbf2]" data-testid="insights-newsletter-section"><div className="mx-auto grid max-w-[1320px] gap-8 px-5 py-20 lg:grid-cols-[1fr_0.8fr] lg:items-end lg:px-8 lg:py-28"><div><Eyebrow>One considered note / month</Eyebrow><h2 className="mt-5 max-w-2xl font-serif text-5xl leading-none tracking-tight">Good ideas should travel.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-[#b9b1a2]">Join the Luminor letter for practical thoughts on making brands more memorable, useful, and alive.</p></div><Link to="/contact" className="inline-flex w-fit items-center rounded-full bg-[#ffbf00] px-6 py-3.5 text-sm font-semibold text-[#1a1814]" data-testid="insights-newsletter-cta">Join the letter <ArrowRight className="ml-2 size-4" /></Link></div></section>
  </main></PageShell>;
}